name = "test-build-cloudflare-pages"
compatibility_date = "2024-05-01"

[build]
command = "npx @cloudflare/next-on-pages build"

[site]
bucket = ".vercel/output/static"

[functions]
directory = ".vercel/output/functions"
