name = "shopify-next-app-frontend"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-05-01"

[build]
command = "npx @cloudflare/next-on-pages build"

[site]
bucket = ".vercel/output/static"

[functions]
directory = ".vercel/output/functions"
